name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool libtool-bin

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer python-for-android==2023.9.16

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'

      - name: Install Android SDK tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        env:
          ANDROID_SDK_ROOT: $ANDROID_HOME

      - name: Build APK
        run: |
          p4a apk --private . \
                  --package=com.jbhugh.songtabfinder \
                  --name="SongTabFinder" \
                  --version=1.0 \
                  --bootstrap=sdl2 \
                  --requirements=python3,kivy,sounddevice,cffi,libportaudio2 \
                  --arch=arm64-v8a \
                  --minsdk=21 \
                  --sdk-dir=$ANDROID_HOME
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: songtabfinder-apk
          path: ./*.apk
