name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer python-for-android

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'  # Latest stable Android SDK as of March 2025

      - name: Build APK
        run: |
          p4a apk --private . \
                  --package=com.jbhugh.songtabfinder \
                  --name="SongTabFinder" \
                  --version=1.0 \
                  --bootstrap=sdl2 \
                  --requirements=python3,kivy,sounddevice,cffi \
                  --depend=libportaudio \
                  --arch=arm64-v8a \
                  --minsdk=21 \
                  --sdk-dir=/home/runner/android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: songtabfinder-apk
          path: ./*.apk
