name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool libtool-bin zlib1g-dev unzip

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK Command-Line Tools
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip || { echo "wget failed"; exit 1; }
          ls -lh cmdline-tools.zip || { echo "Download failed or file missing"; exit 1; }
          mkdir -p /home/runner/android/sdk/cmdline-tools/latest
          unzip cmdline-tools.zip -d /home/runner/android/sdk/cmdline-tools/latest || { echo "Unzip failed"; exit 1; }
          rm cmdline-tools.zip

      - name: Accept Android SDK licenses
        run: |
          yes | /home/runner/android/sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=/home/runner/android/sdk --licenses || true
          yes | /home/runner/android/sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=/home/runner/android/sdk --licenses || true

      - name: Install Android SDK tools
        run: |
          /home/runner/android/sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=/home/runner/android/sdk --verbose "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"

      - name: Debug SDK Installation
        run: |
          echo "ANDROID_HOME is $ANDROID_HOME"
          ls -la $ANDROID_HOME
          ls -la $ANDROID_HOME/build-tools || echo "build-tools folder not found"
        env:
          ANDROID_HOME: /home/runner/android/sdk

      - name: Build APK
        run: |
          buildozer -v android debug
        env:
          ANDROIDSDK: /home/runner/android/sdk
          ANDROIDNDK: /home/runner/android/sdk/ndk/25.2.9519653

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: songtabfinder-apk
          path: ./bin/*.apk
