name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Android SDK and NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d /usr/local/lib/android
          rm sdk-tools.zip
          yes | /usr/local/lib/android/cmdline-tools/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk "platforms;android-33" "build-tools;33.0.0" "ndk;25.1.8937393"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy python-for-android

      - name: Build APK
        env:
          ANDROIDSDK: /usr/local/lib/android/sdk
          ANDROIDNDK: /usr/local/lib/android/sdk/ndk/25.1.8937393
        run: |
          p4a apk --private . --package=com.jbhugh.songtabfinder --name="SongTabFinder" --version=1.0 --bootstrap=sdl2 --requirements=python3,kivy --arch=arm64-v8a --minsdk=21

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: songtabfinder-apk
          path: SongTabFinder*.apk
