name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool libtool-bin zlib1g-dev libffi-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'

      - name: Install Android SDK tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;36.0.0" "ndk;25.2.9519653"
        env:
          ANDROID_SDK_ROOT: $ANDROID_HOME

      - name: Build APK
        run: |
          buildozer -v android debug
        env:
          ANDROIDSDK: $ANDROID_HOME
          ANDROIDNDK: /usr/local/lib/android/sdk/ndk/25.2.9519653

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: songtabfinder-apk
          path: ./bin/*.apk
