name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy python-for-android

      - name: Build APK
        run: |
          p4a apk --private . --package=com.jbhugh.songtabfinder --name="SongTabFinder" --version=1.0 --bootstrap=sdl2 --requirements=python3,kivy --arch=arm64-v8a --minsdk=21 --ndk-version=25.1.8937393

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: songtabfinder-apk
          path: SongTabFinder*.apk
