name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK and NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          mkdir -p /home/runner/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d /home/runner/android-sdk/cmdline-tools
          mv /home/runner/android-sdk/cmdline-tools/cmdline-tools /home/runner/android-sdk/cmdline-tools/latest
          rm sdk-tools.zip
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/home/runner/android-sdk "platforms;android-33" "build-tools;33.0.0" "ndk;25.1.8937393" --verbose
          ls -R /home/runner/android-sdk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython kivy python-for-android

      - name: Build APK
        env:
          ANDROIDSDK: /home/runner/android-sdk
          ANDROIDNDK: /home/runner/android-sdk/ndk/25.1.8937393
        run: |
          p4a apk --private . --package=com.jbhugh.songtabfinder --name="SongTabFinder" --version=1.0 --bootstrap=sdl2 --requirements=python3,kivy,sounddevice --arch=arm64-v8a --minsdk=21 --sdk-dir=/home/runner/android-sdk
          ls -l /home/runner/.local/share/python-for-android/dists/*/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: songtabfinder-apk
          path: /home/runner/.local/share/python-for-android/dists/*/build/outputs/apk/debug/*.apk
